_wandb:
    value:
        cli_version: 0.18.1
        m:
            - "1": pstep
              "6":
                - 3
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 7
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
backbone:
    value: "4"
background_type:
    value: sub
clip:
    value: 2
conf_penalty:
    value: 0
dropout:
    value: 0.1
fold:
    value: 2
gpu:
    value: 1,2
histogram:
    value: true
learning_rate:
    value: 8e-05
m:
    value: 0.99
mask_upsample:
    value: interpolate
noise_level:
    value: 1
note:
    value: ""
refine_mode:
    value: residual
refine_see_bg:
    value: false
refine_steps:
    value: 1
steps:
    value: 20000
temp:
    value: 4
weight_decay:
    value: 0.01
